### ISSUE TITLE
User log in when registering

### ISSUE THREAD

**Issue by jeremydanner** [schiedel-sweden/API#9]
Now a user gets logged in when registering a new user. Because this is an internal tool, we do not want third-party users to create an account. Registered users may then create an account for new users. Now that a user creates an account, the application tries to log in the user. This causes the application to crash because there is already a logged in user. 
### We would like a user to be created without the application trying to log in. 

[We use the default Laravel Auth class](https://laravel.com/docs/5.5/authentication)

**Comment by wrillrysata** [comment]
@jeremydanner I can give this a shot

**Comment by jeremydanner** [comment]
Topp! Much appreciated @Ijebusoma

**Comment by alihossein** [comment]
I did not understand
Do you want to have two users log in at the same time in one system?

**Comment by jeremydanner** [comment]
@alihossein no. We do not want 2 users logged in. We have a bug: "trying to log in a user when creating a new user".

**Comment by wrillrysata** [comment]
So, I've set it up locally now. From what I see, when you are logged in, and you click "Register New User", it logs in the new user you're trying to register while you're still logged in. So, it's logging in 2 users at once. If I'm correct that's what you mean? cc @jeremydanner

**Comment by jeremydanner** [comment]
That's correct! We want to create a new user but we do not want to log the new user in to the system. Current user should still be logged in and redirect them to the index page. @Ijebusoma

**Comment by wrillrysata** [comment]
Okay, got it.

**Comment by shrink** [comment]
The Laravel authentication system isn't designed for the users-register-users use case, it is not a simple configuration change, it would require implementing a new endpoint for managing the creation of accounts. Furthermore, users-register-users is a problematic pattern because it depends on a user creating a password for another user: this encourages poor security.

A more secure approach would be to either have a multi-use invite code that the registration form requires (which registered users can provide to new users), or have a one-time use invite link system that allows registered users to create an invite link that one person can use to register an account at a time.

A multi-use invite code is the easiest method to implement, however, a one-time use invite link system is more secure. This approach would allow the site to continue to use the Laravel authentication system as it is intended: for self-registration. 

I am happy to implement either method (including registration emails as per #10), however, I haven't started work on it as I am unsure if @Ijebusoma is working on an implementation. Please let me know if you'd like me to proceed with implementing either strategy :-)

**Comment by shrink** [comment]
I submitted a PR #14 covering an example of how a multi-use config defined invite code might work. Feel free to discard my PR if Ijebusoma has their own fix for this issue, as they claimed the issue first.

**Comment by jeremydanner** [comment]
Thank you @citricsquid I will review your PR over the weekend. Cheers!
